[package]
name = "json2rdf"
version = "0.1.1"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
log = "0.4.22"
oxrdf = "0.1.7"


serde = "1.0.203"
serde_json = "1.0.117"
uuid = { version = "1", features = ["v4"] }
