[package]
name = "json2rdf"
version = "0.1.0"
edition = "2021"

[dependencies]
oxrdf = "0.1.7"
petgraph = "0.6.5"

serde = "1.0.203"
serde_json = "1.0.117"
struson = "0.5.0"
uuid = { version = "1", features = ["v4"] }
